# Generated by Django 5.0.6 on 2024-08-13 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='central_letter',
            field=models.CharField(db_index=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='characters',
            field=models.CharField(db_index=True, max_length=6, unique=True),
        ),
    ]
