# Generated by Django 5.0.6 on 2024-08-20 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bee', '0002_alter_puzzle_central_letter_alter_puzzle_characters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergame',
            name='status',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
