# Generated by Django 5.0.6 on 2024-08-21 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bee', '0003_alter_usergame_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergame',
            name='foundWords',
            field=models.JSONField(default=list),
        ),
    ]
